# src/main/resources/application.yml
okta:
  oauth2:
    issuer: https://dev-h7c8tfbibzk0nnyn.us.auth0.com/
    client-id: FbvzvoCdWhWQne3W7tSDwSinqriGr2Iq
    client-secret: vHo12QYN6gAIpqWjHyu1jzH0fHhC7rrzbV6i_GuQOIMSFBGHau8sIN0yBXlGrLAS

# The sample and instructions above for the callback and logout URL configuration use port 3000.
# If you wish to use a different port, change this and be sure your callback and logout URLs are
# configured with the correct port.
server:
  port: 3000